class InventoryError(Exception):...

class InventoryOverflowError(InventoryError):...

class InventoryDeleteError(InventoryError):...

class InventoryUpdateError(InventoryError): ...


class ItemIdError(InventoryError):...
